{
 "title": "Docker Dash",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Container Actions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "engine_daemon_container_actions_seconds_bucket"
    }
   ]
  },
  {
   "title": "Docker Failed Checks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "engine_daemon_health_checks_failed_total"
    }
   ]
  },
  {
   "title": "Docker Health Checks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "engine_daemon_health_checks_total"
    }
   ]
  },
  {
   "title": "Docker Network",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "engine_daemon_network_actions_seconds_count"
    },
    {
     "expr": "engine_daemon_container_actions_seconds_sum"
    }
   ]
  },
  {
   "title": "Docker CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "engine_daemon_engine_cpus_cpus" }
   ]
  }
 ]
}